## 1 - Building basic functions with numpy

In [ ]:
import numpy as np
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
import time

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic = time.time()
c= np.dot(a,b)
toc=time.time()
print(c)
print("Vectorized version:" +  str(1000*(tic-toc)) + "ms")



c=0
tic= time.time()
for i in range(1000000):
  c+= a[i]*b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(tic-toc)) + "ms")

249935.64673896998
Vectorized version:-1.5747547149658203ms
249935.64673898258
For loop:-487.9889488220215ms


###1.1 - sigmoid function, If we import Math libraries

In [ ]:
import math

def basic_sigmoid(x):

    s=1/(1+math.exp(-x))

    return s

In [ ]:
basic_sigmoid(3)

0.9525741268224334

In [ ]:
import numpy as np

x= np.array([1,2,3,4])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


### If we import Numpy 


In [ ]:
print(x+3)

[4 5 6 7]


In [ ]:
def sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s


In [ ]:
x= np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

##1.2 - Sigmoid gradient
As you've seen in lecture, you will need to compute gradients to optimize loss functions using backpropagation. Let's code your first gradient function.

###Exercise: 
Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. 

The formula is:

sigmoid_derivative(x)=σ′(x)=σ(x)(1−σ(x))
You often code this function in two steps:

Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
Compute σ′(x)=s(1−s)

In [ ]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = s*(1-s)
    return ds

In [ ]:
x=np.array([1,2,3])
print("Sigmoid_derivative(x)= " + str(  sigmoid_derivative(x)))

Sigmoid_derivative(x)= [0.19661193 0.10499359 0.04517666]


##1.3 - Reshapping Arrays

In [ ]:
 def image2vector(image):

     
     v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
     return v 

In [ ]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print("image2vector(image)=" + str(image2vector(image)))

image2vector(image)=[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


## 1.4- NormalizingRows

In [ ]:
def normalizerows(x):
    
    norm_rows=np.linalg.norm(x,axis=1,keepdims=True)
    x=x/norm_rows
    return x

In [ ]:
x = np.array([
              [0,3,4],
              [1,6,4]
])

print("Normalize_rows(x) =" + str(normalizerows(x)))

Normalize_rows(x) =[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


##1.5 - Broadcasting and the softmax function

In [ ]:
def softmax(x):
     
     x_exp = np.exp(x)
     x_sum =np.sum(x_exp, axis=1, keepdims=True)
     s= x_exp/x_sum
     return s
     

In [ ]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])

print("Softmax(x) =" + str(softmax(x)))

Softmax(x) =[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


##2) Vectorization

In [ ]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

tic= time.process_time()
dot= 0
for i in range(len(x1)):
  dot+=x1[i]*x2[i]
  toc = time.process_time()
  print("dot :" + str(dot) + "computation time" + str(1000*(toc-tic)) + "ms")

dot :81computation time0.09922099999926104ms
dot :85computation time0.5971349999995823ms
dot :95computation time0.6951229999998532ms
dot :95computation time0.739711000001364ms
dot :95computation time0.7884000000011326ms
dot :158computation time0.8449520000013422ms
dot :168computation time0.9007889999992358ms
dot :168computation time0.9654979999993429ms
dot :168computation time1.012077000002165ms
dot :168computation time1.0567190000010385ms
dot :249computation time1.1045359999997117ms
dot :253computation time1.1519389999996577ms
dot :278computation time1.1987799999992887ms
dot :278computation time1.233424000002259ms
dot :278computation time1.2902920000001927ms


In [ ]:
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i,j] =  x1[i]*x2[j]
    print("Outer :" + str(outer) + "computation time" + str(1000*(toc-tic)) + "ms")

**If We Use Vectorized Dot Products**

In [ ]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot:" + str(1000*(toc-tic)) + "ms")

dot:1.0834220000006667ms


In [ ]:
outer = np.outer(x1,x2)
print("outer:" + str(1000*(toc-tic)) + "ms")

outer:1.0834220000006667ms


##2.1 Implement the L1 and L2 loss functions

In [ ]:
def L1(yhat,y):
    
    loss1 = sum(abs(yhat-y))
    return loss1


In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


**If We Use Vectorized Dot Products for Loss function**


> Implement the numpy vectorized version of the L2 loss.



In [ ]:
def L2(yhat,y):
     
     x = yhat-y
    
     loss2 = np.dot(x,x)
     return loss2

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
